### PR TITLE
fix for compilation error against firmware v 0.4.7

### LINKED ISSUE #54: Compilation Issues
I used this a few days ago without any issue. Today when I try to verify the firmware code it fails. Below you'll find a copy/paste of the compilation attempt. 

voodoo.cpp:37:0: warning: "DEBUG" redefined [enabled by default]
 
 ^
In file included from ../services/inc/debug.h:1:0,
                 from ../wiring/inc/spark_wiring.h:36,
                 from ./inc/application.h:36,
                 from voodoo.cpp:35:
../services/inc/service_debug.h:109:0: note: this is the location of the previous definition
 #define DEBUG(fmt, ...)
 ^
voodoo.cpp: In function 'long unsigned int pingRead(int)':
voodoo.cpp:422:45: error: call of overloaded 'pulseIn(int&, PinState)' is ambiguous
 
                                             ^

voodoo.cpp:422:45: note: candidates are:
In file included from ./inc/application.h:36:0,
                 from voodoo.cpp:35:
../wiring/inc/spark_wiring.h:82:10: note: uint32_t pulseIn(pin_t, uint16_t)
 uint32_t pulseIn(pin_t pin, uint16_t value);
          ^
voodoo.cpp:375:15: note: long unsigned int pulseIn(uint16_t, uint8_t)
  * Original pulseIn Function for the Spark Core - Version 0.1.1 (Beta)
               ^
voodoo.cpp: In function 'int ToServoIndex(int)':
voodoo.cpp:242:1: warning: control reaches end of non-void function [-Wreturn-type]
     if (pin == 0 || pin == 1 || pin == 2 || pin == 3) return pin;
 ^
make[1]: *** [../build/target/user/platform-6voodoo.o] Error 1
make: *** [user] Error 2
Error: Could not compile. Please review your code.

### PR DESCRIPTION
**Pull request by Gabriel-Lacatus**
Fixes #54

### CODE REVIEW

**Comment by edsadr** [comment]
:+1:  please merge

**Comment by BrianGenisio** [comment]
I ran into this tonight.  Before this gets merged, I have two questions about this:

1. First, this problem exists because the 0.4.7 firmware introduces a [pulseIn](https://docs.particle.io/reference/firmware/photon/#pulsein-) function.  By keeping our name the same as the system `pulseIn`, I fear that we don't know for certain that our function will be called.  Instead of casting and hoping it disambiguates properly, how about changing the function to `pingPulseIn` or something... that way we are disambiguating by name, not by casted parameters?

2. Along the same lines, do we even need our own `pulseIn` any longer?  Can we just delete our implementation of `pulseIn` and use the system version, if it exists?  It might require a `#define` so it works with old firmwares.

**Comment by Gabriel-Lacatus** [comment]
The naming collision is a bit unfortunate. From looking at the code of both functions it looks like they are doing fairly similar things but I notice at least two differences that have external effect:
 1. The system function times out after 3 seconds whereas the voodoospark one times out in 10 seconds
 2. The system function waits until the pin reaches the opposite state before starting to count whereas the voodoospark function starts counting directly if the pin is already in the desired state at the time of the function call

I guess the timeout discrepancy is not terribly problematic but the second difference might cause slightly different outcomes in some cases?

**Comment by BrianGenisio** [comment]
Knowing this, I'd prefer to just change the name of `pulseIn` to `pingPulseIn` to avoid the name collision completely, but maintain compatibility with the ping command.  It would be awesome if we can get this merged soon.  We have to flash 110 chips pretty soon here... it would help if we can use an official drop of the firmware.

@rwaldron Do you agree with this?

**Comment by rwaldron** [comment]
@BrianGenisio yeah, `pingPulseIn` is legit. I'll land this and then change the name entirely. Thanks everyone.

**Comment by rwaldron** [comment]
https://github.com/spark/particle-cli/pull/169

**Pull request merged**
